### ISSUE TITLE
Add compatibility for VotifierEvent to be fired on /vote claim

### ISSUE THREAD

**Issue by extendedclip** [teozfrank/UltimateVotes#1]
Would be nice to see a VotifierEvent be fired on the server a player claims a vote on. This would allow compatibility with other vote reward plugins.

To implement this you would only need to add the package and classes containing the Vote object and VotifierEvent and then fire that event when a player claims the reward on a specific server (spigot side)

**Comment by teozfrank** [comment]
The only problem with implementing this would be that the votifier plugin would be required on that server which defeats the purpose. If you try to implement that you will get a ClassNotFoundException as votifier wont be on that server, If I add the code from votifier I would be breaking the terms of the license it uses. The problem with this is votifier isn't designed for networks, It could be implemented in single servers but there is no point as the votifier event is triggered anyway.

**Comment by extendedclip** [comment]
Well yeah, I do suggest you package the classes within your plugin rather than require Votifier be installed. I do know the plugin is GPL so packaging it within your plugin (in the original package name) should not be an issue as long as they aren't obfuscated and the license be provided as well.

**Comment by extendedclip** [comment]
If the licensing aspect is something you don't want to deal with, maybe even fire your own custom event when a vote is being claimed so other plugins can utilize your custom event like they would the VotifierEvent? Idk, I have just had many requests to add support for UltimateVotes with VoteParty but since you don't require Votifier to be installed server side I am trying to find a solution to know when a player voted.

**Comment by teozfrank** [comment]
The other side to GPL is that if I use any code that is GPL v3 I have to make my entire project GPL v3 (this is different than implementing an API), sorry but I am not doing that. 

Another solution would be to use plugin messaging but again that requires a player to be on that server for the message to be even sent. (which works fine for rewarding players as they have to be online anyway). Adding it to the claim command wont work for servers that have claiming disabled. 

The solution would be to have a bungee plugin, relying on a spigot plugin alone for what you are doing is simply the wrong way for a bungeecord network. My suggestion would be to create a bungeecord version of your plugin. You can then listen to the vote event of the bungeecord voting and get who voted that way.

**Comment by extendedclip** [comment]
I only want to add votes to my counter for servers that votes are claimed on. It wouldnt make sense for me to create a bungee plugin just to listen to the event and send a plugin message to all servers when a vote is received. I would also not have any way of telling which server a player claimed the vote on. It would really make more sense for you to simply fire an event such as a "PlayerClaimVoteEvent" or something of that nature which would allow me to hook into in my plugin and act accordingly when a vote is claimed.

**Comment by teozfrank** [comment]
Ok but what about if vote claiming is disabled?

**Comment by extendedclip** [comment]
Well if claiming is disabled on a specific server, I don't see what sense it would make to have my plugin installed on it.

**Comment by teozfrank** [comment]
If claiming is disabled, that doesn't mean players cant be rewarded... I think what you need is an event when a player is rewarded instead of claiming.

**Comment by aaomidi** [comment]
I disagree with this, could cause a ton of issues.

**Comment by teozfrank** [comment]
Closed due to being an inviable suggestion.
