### ISSUE TITLE
UUID Resolving not working correctly

### ISSUE THREAD

**Issue by thunderlight411** [teozfrank/UltimateVotes#11]
Got an issue with storing votes for offline players with the UUID catching, is this an issue caused by UltimateVotes?

Sometimes when a player is offline or online and votes for our server more than 1 UUID appearing in the console and the db storage.
![15bf20429fb76d6961cd6569de9e94f898fcf514](https://user-images.githubusercontent.com/4320849/29271761-6a2950dc-80fd-11e7-8f09-821aeaf6e5ad.jpg)

Also see the debugged console text while this player is voting (offline)
[debug.txt](https://github.com/teozfrank/UltimateVotes/files/1222201/debug.txt)

p.s. its a Standalone server

**Comment by teozfrank** [comment]
Standalone online or offline server?

**Comment by teozfrank** [comment]
I see what is happening I will look into it further. What version of Spigot and can you provide a list of voting sites you are using too please.

**Comment by thunderlight411** [comment]
Hi Frank,

We are using spigot version 1.12.2
The sites that we are using.

Serverpact.nl
minecraftkrant.nl
minecraftforum.net
planetMinecraft.com
Minecraft-server-list.com
Minecraftlist.org
minecraft-mp.com

Kind Regards,
Marco

**Comment by teozfrank** [comment]
Was the player offline here?
https://gyazo.com/3065e6bebda6b5d6cc05c3de79854f7c

And online here? 
https://gyazo.com/4113e366651b3acd55ea1c2bcc23dad4

The only reason why the server would use a cached UUID is if the player joined the server. Once I know when the player was offline / online I can get a better idea, thanks.

**Comment by thunderlight411** [comment]
no longer active
