### ISSUE TITLE
Offline Voting Claim issue...

### ISSUE THREAD

**Issue by mrcoffee1026** [teozfrank/UltimateVotes#12]
If a command is run after user has achieved X number of votes, that reward is not given, only the default rewards are provided during claims.

Unrelated:
If user is OP, vote reminders are not given?

**Comment by teozfrank** [comment]
Please provide a copy of your config.yml (no mysql details) and rewards.yml is your server a standalone server or network?

Yes as they would have all permissions, the permission is -> ultimatevotes.votereminder.bypass

**Comment by mrcoffee1026** [comment]
Standalone Version
config:
```
# --------------------------------------------------------------------
# Copyright (c) teozfrank 2014 ,All Rights Reserved
# This plugin is a purchase from SpigotMC
# If you did not purchase this please contact the plugin owner
# Distribution of this plugin is against the terms of this plugin.
# --------------------------------------------------------------------
# signwall layout variables
# you can use colour codes here :)
# %postion% the postion in the top 10 voters they are can be a value of 1-10
# %playername% the players name
ultimatevotes:
    configversion: 2.5
    checkforupdates: false
# mysql settings
    mysql:
        enabled: true
        host: 'localhost'
        port: '3306'
        database: 'ultimatevotes'
        user: 'uvotesTwentyOne'
        pass: 'myPassWordIsABetter1ThanYours'
        maintainconnection: true
# reward settings
    rewards:
        enabled: true
        rewardsbyworld: false
        claiming:
            useclaimcommand: true
            rewardonline: true
            useclaimgui: true
# vote settings
    votes:
        usingbungeecord: false
# set loadonstartup to true when you have enabled mysql
        loadonstartup: true
        autoreloadvotesinterval: 12000
        broadcast:
# does the voting player have to be online for the broadcast to take effect?
            online: false
# are the vote broadcasts enabled?
            enabled: true
        votereminder:
            enabled: true
            interval: 30000
            disabledworlds:
              - 'exampledisabledworld'
        joinmessage:
            enabled: true
# debug settings
    debug:
        enabled: false

```
rewards:
```
# --------------------------------------------------------------------
# Copyright (c) teozfrank 2014 ,All Rights Reserved
# This plugin is a purchase from SpigotMC
# If you did not purchase this please contact the plugin owner
# Distribution of this plugin is against the terms of this plugin.
# --------------------------------------------------------------------
# each number is the amount of votes for that command to be performed, you may change this
# to your own liking and there can be unlimited rewards.
# example rewards
# there are three types; normal, delayed and percentage chance rewards.
#
##############################################################
# normal commands are ran as normal and look like this
#
# 'fly %player%'
#
##############################################################
# delayed rewards look like this
#
# '1;fly %player%'
#
# 1 means the time in minutes when this command will be ran
# this is seperated with a ';' where the command is put on the right
# it can be any command you could add / remove a permission too
# note this command will be forced to run if the server is restarted
# it does not persist.
##############################################################
# percentage chance rewards look like this
#
# '1/100;fly %player%'
#
# the above example has a 1 in 100 chance if being ran
##############################################################
# multiple commands can be used for both delayed rewards and percentage rewards
#
# '1/100;fly %player%;msg %player% you have been given fly!'
# '1;fly %player%; msg %player% you have been given fly
#
##############################################################
# Please do not touch the config version or you will break the plugin!
configversion: 1.4
repeatingrewards:
# default repeating reward used if reward by world is disabled
   default:
     - 'eco give %player% 35'
     - 'msg %player% Thank you for voting!  $35 has been added to your account!'
     - 'crates key %player% Vote'
     - 'griefprevention:adjustbonusclaimblocks %player% 35'
     - 'broadcast &b%player%&r &9has voted for the server and earned $35 and 35 claim blocks!  You can too, /vote to see how!'
# repeating rewards by world "world" is just an example world name
#   world:
#     - 'give %player% 18 1'
rewards:
# these rewards are when a player reaches a certain amount of votes
  '6':
     - 'lp user %player% promote voter'
     - 'broadcast &b%player%&r &9has been promoted to &2&l[Turtle]&r&9!'
  '15':
     - 'lp user %player% promote voter'
     - 'broadcast &b%player%&r &9has been promoted to &7&l[Kitten]&r&9!'
  '25':
     - 'lp user %player% promote voter'
     - 'broadcast &b%player%&r &9has been promoted to &6&l[Puppy]&r&9!'
  '50':
     - 'lp user %player% promote voter'
     - 'broadcast &b%player%&r &9has been promoted to &9&l[Penguin]&r&9!'
  '125':
     - 'lp user %player% promote voter'
     - 'broadcast &b%player%&r &9has been promoted to &d&l[Pig]&r&9!'
  '200':
     - 'lp user %player% promote voter'
     - 'broadcast &b%player%&r &9has been promoted to &b&l[Rhino]&r&9!'
  '350':
     - 'lp user %player% promote voter'
     - 'broadcast &b%player%&r &9has been promoted to &7&l[Shark]&r&9!'
  '500':
     - 'lp user %player% promote voter'
     - 'broadcast &b%player%&r &9has been promoted to &7&l[Lion]&r&9!'
  '1000':
     - 'griefprevention:adjustbonusclaimblocks %player% 2000'
     - 'eco give %player% 1000'     
     - 'broadcast &b%player%&r &9has been given &f&l2000&r &9extra claim blocks and &f&l$10K&r &9 for reaching 1000 votes!'
# these rewards are the same as above but per world if rewards by world are enabled
#  world:
#     '10':
#        - 'give %player% 6 1'
#        - 'say %player% has reached 10 votes'
#     '21':
#        - 'give %player% 260 1'
#     '29':
#        - 'give %player% 38 1'
```

and thanks for the info on that permission.

**Comment by teozfrank** [comment]
Apologies for the delay, is your server an online or offline mode server?

**Comment by mrcoffee1026** [comment]
Online mode.

**Comment by teozfrank** [comment]
Can you please provide a list of voting sites you are using too please.

**Comment by mrcoffee1026** [comment]
http://www.minecraftforum.net
http://minecraft-server-list.com
http://minecraftservers.org
http://topg.org
https://www.planetminecraft.com
http://minecraft-mp.com

**Comment by mrcoffee1026** [comment]
Issue persists, if they're claiming for offline votes, the
# default repeating reward used if reward by world is disabled
section is awarded but the 
# these rewards are when a player reaches a certain amount of votes
section is not.

Thanks.

**Comment by teozfrank** [comment]
Ok, has it rewarded any of the cumulative rewards? Do you have any server logs you can post? Can you enable debug mode in the config.yml and show you voting on each of the voting sites and sending me the resulting logs please?

**Comment by mrcoffee1026** [comment]
Actually the only cumulative reward I have set up is rank increase.  I know it's not doing this as I have to manually do it later.  I'd have to kind of set up a situation where I can test this but the sites do limit votes to the IPs so doing the test isn't super easy.  I may see if I can use your test method to acquire votes for an offline player then go back and claim, I have no idea if that would have the identical issue or not, but I'll give that a try.  I can say for sure I'm not getting errors during the claim process into my server logs.   Anyway i'll have to try some things just to generate these logs for you... If it's possible i'll try with my local test build if it even works, I somehow think the listener set up may not but I'll see and get back... will post later, thanks.

**Comment by mrcoffee1026** [comment]
OK I rechecked this using the testvote on my player... and... it's giving the cumulative rewards TWICE.  Either fixing the text with the monthly votes has caused rewarding to use monthly votes again instead of alltime votes... or I don't even know.  My first cumulative is at 6 votes, the next at 15.  I vote for him 6 times.  Claiming any one of these votes causes him to promote.  Claiming the remaining of the 6 votes... causes him to be promoted again.  Happens again... I give him another 9 test votes, claiming any of them, the count is registered at 15 so... he gets promoted... and then again when he claims his 15th vote.  Now this is with the testvote feature... I've not witnessed this with the live working votes except back before there was an option to use the cumulative total instead of the monthly total for cumulative rewards.  

rewards.yml https://pastebin.com/7V0B9pty
serverlogs with debug enabled: https://pastebin.com/wuSWrz8B

**Comment by mrcoffee1026** [comment]
Ok trying this with live sites this time.  My test user is CoffeeTheMug.  I have given him an impossible combination of counts for the greatest amount of activity.  12 Monthly votes, 0 Alltime.

Logs during experiment:
https://pastebin.com/z2eQW9pX

No promotion of any sort, oddly enough.  Nothing like the too many promotions of the testvote situation, just nothing happened instead.

**Comment by mrcoffee1026** [comment]
And sorry I neglected your first question,  yes it does award cumulative as long as the user is online while voting.

**Comment by teozfrank** [comment]
This is quite an old issue which I am pretty sure this is fixed, please re-open a new issue if it is not and I will get on to it right away.
