### ISSUE TITLE
API site down?

### ISSUE THREAD

**Issue by FrankHeijden** [teozfrank/UltimateVotes#16]
Hey,

http://fjfreelance.com/javadocs/ultimatevotesapi/ seems to be down:

This site can’t be reached
fjfreelance.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by teozfrank** [comment]
Yes, the domain expired, it is now been moved here -> https://teoz.jrnetwork.net/ultimatevotesapi/
