### ISSUE TITLE
mtop showing alltime count instead of monthly count...

### ISSUE THREAD

**Issue by mrcoffee1026** [teozfrank/UltimateVotes#17]
This may be due to the feature you added where awards are given for alltime count instead of monthly, which is absolutely needed... changing this option shouldn't cause the mtop to show the alltime count though since there's a separate function for that, right?

**Comment by mrcoffee1026** [comment]
Pleasee add %monthlyvotecount% placeholder for use in messages to remedy.

**Comment by mrcoffee1026** [comment]
If you're not going to continue support for this can you at least post the source?  I tried decompiling but it's a disaster... awesomely descriptive .class/.java and even folder names being a-e.  Takes some study of any file to figure out what it even does, and the directory structure is copied like 3 times so any file in a similar location might be the one that I actually need to adjust, it is a disaster trying to figure out.

**Comment by teozfrank** [comment]
The project is obfuscated for that exact reason, to put off someone de-compiling it and modifying it, Can you post your config.yml please

**Comment by teozfrank** [comment]
Found the problem, please let me know if this fixes your problem in case I missed anything ->https://www.spigotmc.org/resources/ultimatevotes-1-12-2-spigot-bungeecord-uuid.516/update?update=219104

**Comment by mrcoffee1026** [comment]
This looks like it is working perfectly now, thank you again!!!

**Comment by mrcoffee1026** [comment]
Whatever you did to fix this just broke the cumulative rewards system again.  Now users are being given cumulative rewards on monthly counts again.  Please fix this some other way so that the
```
    cumulativerewards:
      rewardbymonthlyvotescount: false
```
setting is obeyed.
