### ISSUE TITLE
Require player to be online for a vote to work

### ISSUE THREAD

**Issue by aaomidi** [teozfrank/UltimateVotes#2]
Some people want to use this plugin on systems like [lilypadmc](http://lilypadmc.org/). I already have created a vote bridge between the servers, it would be awesome if we can only apply the votes when the player is online and having no vote claiming.

Thanks

**Comment by teozfrank** [comment]
Sorry but support is currently only for spigot and bungeecord. This feature already works in bungeecord. Players are rewarded if they are online.

**Comment by aaomidi** [comment]
Whats wrong with just adding one config option? :/

**Comment by teozfrank** [comment]
There is a config option, claiming can be turned off which enables voting when the player is online.

**Comment by teozfrank** [comment]
closed as no response made, the plugin already allows disabling of claiming.
