### ISSUE TITLE
/uv setwallsigns

### ISSUE THREAD

**Issue by Ironic8b498** [teozfrank/UltimateVotes#27]
I get this error when I run /uv setwallsigns

https://paste.helpch.at/ihurawalov.bash

 I believe its caused by worldedit-bukkit-7.0.0-SNAPSHOT-dist.  Minecraft version is 1.13.2

**Comment by teozfrank** [comment]
Yes please use an earlier version of worledit if possible

**Comment by Ironic8b498** [comment]
same version just a earlier release or go down one version, which will not run on the server?

**Comment by teozfrank** [comment]
use the latest stable version and see does it work.

**Comment by teozfrank** [comment]
Closing as no response made, if you are still experiencing issues please re open a new issue.
