### ISSUE TITLE
Duplicate entry for key 'PLAYER'

### ISSUE THREAD

**Issue by ghost** [teozfrank/UltimateVotes#28]
When some of my players vote, these two messages get shown in the console, and they do not get rewarded. 

[17:41:12 INFO]: [UltimateVotes] [Severe] Duplicate entry '[username]' for key 'PLAYER'
[17:41:12 INFO]: [UltimateVotes] [Severe] Duplicate entry '[username]' for key 'PLAYER'
(In the console messages "[userame]" is replaced by the voting player's username.)

UltimateVotes version 1.8.2
(Edit: We updated to 1.8.5 and it's still happening) 
Server version Paper 1.13.2

**Comment by teozfrank** [comment]
Updating wont solve the problem, your database has an offline uuid and online uuid for the same player and one of which has to be removed. Is your server standalone or a bungeecord server? Is it online mode or offline?

**Comment by ghost** [comment]
It's a BungeeCord server (so it's technically offline mode, but ip_forward is enabled), but UltimateVotes is only running on 1/4 servers, so we set it up like a single Spigot server (usingbungeecord: false). Perhaps this is causing it? 

The issue only happens to a select group of players.

**Comment by ghost** [comment]
Sorry for the double post, but is there any new information about this issue or how I can fix it? 

Thanks!

**Comment by teozfrank** [comment]
If its a bungeecord server it can be online or offline dependent on your settings in the bungeecord config file. Is it set to online or offline there? If its online you also need to set bungeecord to true in your spigot.yml of each connected instance, is this the case?

**Comment by teozfrank** [comment]
Could you please join my discord server, you will get better support here -> https://discord.gg/hn8e9tu

**Comment by teozfrank** [comment]
Did you resolve the issue?
