### ISSUE TITLE
MySQL refusing to connect

### ISSUE THREAD

**Issue by Xverion** [teozfrank/UltimateVotes#3]
We've been trying to get this plugin to work for two full days but can't seem to get it to run. We have servers running on multiple boxes. The bungeecord box hosts the MySQL server as well. The proxy plugin connects flawlessly to the MySQL. However the prison server(the one we are testing it on) refuses to connect to the MySQL database on the other box. I've made sure it's not a privilege problem so I'm at a loss here. If i've overlooked something please let me know. The error we receive is MySql could not establish a connection!com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Kind regards Xverion

**Comment by teozfrank** [comment]
Not an issue with the plugin, its an issue on your server setup, make sure the ports are opened (3306 for mysql) etc.

**Comment by Xverion** [comment]
Figured it out. Owner set a very strict ip table.. Sorry to bother you.
