### ISSUE TITLE
trying to add signwall and getting this error in console 

### ISSUE THREAD

**Issue by missycheshire** [teozfrank/UltimateVotes#30]
running spigot 1.14.4
also have worldedit 7.0.1
have wall of signs as instructed on the wiki, pos1 pos2 and this error appears in the console along with 'an internal error occurred while attempting to perform this command in game'
is this happening due to the orientation bug mentioned on the wiki?

06.09 17:26:14 [Server] Server thread/INFO CHARACTERNAME issued server command: /uv setwallsigns
06.09 17:26:14 [Server] Server thread/ERROR null
06.09 17:26:14 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'uv' in plugin UltimateVotes v1.9
06.09 17:26:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
06.09 17:26:14 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.WorldEditPlugin.getSelection(Lorg/bukkit/entity/Player;)Lcom/sk89q/worldedit/bukkit/selections/Selection;
06.09 17:26:14 [Server] INFO at teozfrank.ultimatevotes.util.c.a(FileManager.java:322) ~[?:?]
06.09 17:26:14 [Server] INFO at teozfrank.ultimatevotes.a.d.onCommand(UltimateVotesListener.java:76) ~[?:?]
06.09 17:26:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Spigot_Latest.jar:git-Spigot-065a373-763e560]
06.09 17:26:14 [Server] INFO ... 17 more

**Comment by teozfrank** [comment]
"is this happening due to the orientation bug mentioned on the wiki?"

No its not, the plugin needs to be updated to support newer worldedit versions. Please join the discord where there is an updated development version that should work for you. Please contact me as soon as you join and I will get you the dev version to try.

https://discord.gg/hn8e9tu

**Comment by teozfrank** [comment]
new version of worldedit compatible plugin dev release available on discord. Closed.
