### ISSUE TITLE
Default configuration file - Not Created

### ISSUE THREAD

**Issue by SpyCraft3r** [teozfrank/UltimateVotes#34]
UltimateVotesBungee will create the default configuration file for the plugin. Next stop your bungeecord instance.........**No it isnt creating the config**

**Comment by teozfrank** [comment]
> UltimateVotesBungee will create the default configuration file for the plugin. Next stop your bungeecord instance.........**No it isnt creating the config**

sorry for the delay in responding. Have you got YAMLER installed on bungee?

**Comment by teozfrank** [comment]
Any update @SpyCraft3r ?

**Comment by SpyCraft3r** [comment]
Hey Teos, yes mate that fixed the issue, now I have another issue, the votes are working on the vote sites but nothing is being broadcasted in game or the rewards being given
