### ISSUE TITLE
Command not being ran on vote

### ISSUE THREAD

**Issue by Sotlol1** [teozfrank/UltimateVotes#6]
On vote i want to give the players enjin points and the command for it is "enjin addpoints <player> <amount>". All rewards work fine except for the enjin command there are no errors or anything in the console. It's like the plugin never ran the command

Rewards.yml:

```
# --------------------------------------------------------------------
# Copyright (c) teozfrank 2014 ,All Rights Reserved
# This plugin is a purchase from SpigotMC
# If you did not purchase this please contact the plugin owner
# Distribution of this plugin is against the terms of this plugin.
# --------------------------------------------------------------------
# each number is the amount of votes for that command to be performed, you may change this
# to your own liking and there can be unlimited rewards.
# example rewards
# there are three types; normal, delayed and percentage chance rewards.
#
##############################################################
# normal commands are ran as normal and look like this
#
# 'fly %player%'
#
##############################################################
# delayed rewards look like this
#
# '1;fly %player%'
#
#1 means the time in minutes when this command will be ran
# this is seperated with a ';' where the command is put on the right
# it can be any command you could add / remove a permission too
# note this command will be forced to run if the server is restarted
# it does not persist.
##############################################################
# percentage chance rewards look like this
#
# '1/100;fly %player%'
#
# the above example has a 1 in 100 chance if being ran
##############################################################
# multiple commands can be used for both delayed rewards and percentage rewards
#
# '1/100;fly %player%;msg %player% you have been given fly!'
# '1;fly %player%; msg %player% you have been given fly
#
##############################################################
# Please do not touch the config version or you will break the plugin!
configversion: 1.4
repeatingrewards:
# default repeating reward used if reward by world is disabled
   default:
     - 'give %player% 1 1'
     - 'give %player% 1 1'
# repeating rewards by world "world" is just an example world name
   world:
     - 'enjin addpoints %player% 1'
     - 'give %player% 264 1'
     - '1/100;manuaddp %player% ultracosmetics.hats.golem' 
     - '1/100;manuaddp %player% ultracosmetics.hats.enderman'  
     - '1/100;manuaddp %player% ultracosmetics.hats.mario'  
     - '1/100;manuaddp %player% ultracosmetics.hats.luigi'  
     - '1/100;manuaddp %player% ultracosmetics.hats.batman'  
     - '1/150;manuaddp %player% ultracosmetics.gadgets.melonthrower'   
     - '1/1000;manuaddp %player% ultracosmetics.emotes.cheeky' 
     - '1/1000;manuaddp %player% ultracosmetics.emotes.happy'  
   ASkyBlock:
     - 'enjin addpoints %player% 1'
     - 'give %player% 3 2'
     - '1/100;manuaddp %player% ultracosmetics.hats.golem' 
     - '1/100;manuaddp %player% ultracosmetics.hats.enderman'  
     - '1/100;manuaddp %player% ultracosmetics.hats.mario'  
     - '1/100;manuaddp %player% ultracosmetics.hats.luigi'  
     - '1/100;manuaddp %player% ultracosmetics.hats.batman'  
     - '1/150;manuaddp %player% ultracosmetics.gadgets.melonthrower'   
     - '1/1000;manuaddp %player% ultracosmetics.emotes.cheeky' 
     - '1/1000;manuaddp %player% ultracosmetics.emotes.happy'  
rewards:
# these rewards are when a player reaches a certain amount of votes
# these rewards are the same as above but per world if rewards by world are enabled
  world:

```

**Comment by teozfrank** [comment]
have you tried running the command in console to see does it work? what version of the enjin plugin are you using?

**Comment by Sotlol1** [comment]
Yes, running the command in the console works fine. I'm using the latest version of the plugin. (Spigot Beta Plugin v3.0.20)

**Comment by teozfrank** [comment]
do you have a link for the version you are using please?

**Comment by Sotlol1** [comment]
https://www.spigotmc.org/resources/enjin-cms-donationcraft-plugin.17209/updates

**Comment by teozfrank** [comment]
Using that plugin and the latest build of spigot, the points get added fine -> https://gyazo.com/1885c6a7078e04d312b92f2e0f93cf3b

**Comment by Sotlol1** [comment]
I'm using a 1.9.4 spigot build and is unable to upgrade from it.

**Comment by teozfrank** [comment]
There is nothing I can do then, I only support the latest version of spigot, you will either need to upgrade to get it working or not use that feature. If you enable debug mode you will see that the plugin attempts to execute that command, please correct me if I'm wrong with your logs to show otherwise, thanks.

**Comment by Sotlol1** [comment]
Okey so i did update my server to the latest spigot and in the debug it says "dispatching vote reward: enjin addpoints Sotlol1 1" but i don't get the reward, Like you said

**Comment by teozfrank** [comment]
How do you mean you dont get the reward, can you show me the log of that?

**Comment by Sotlol1** [comment]
![logs](https://cloud.githubusercontent.com/assets/6286246/17642926/7c0a51b6-615a-11e6-9c16-958a45c20500.png)

**Comment by Sotlol1** [comment]
I dispatches the diamond but not the enjin point.

**Comment by teozfrank** [comment]
could you add the enjin reward in the default rewards so it would look like this and let me know does that work? -> 

configversion: 1.4
repeatingrewards:

# default repeating reward used if reward by world is disabled

   default:
     - 'give %player% 1 1'
     - 'give %player% 1 1'
     - 'enjin addpoints %player% 1'

# repeating rewards by world "world" is just an example world name

   world:
     - 'give %player% 264 1'
     - '1/100;manuaddp %player% ultracosmetics.hats.golem' 
     - '1/100;manuaddp %player% ultracosmetics.hats.enderman'  
     - '1/100;manuaddp %player% ultracosmetics.hats.mario'  
     - '1/100;manuaddp %player% ultracosmetics.hats.luigi'  
     - '1/100;manuaddp %player% ultracosmetics.hats.batman'  
     - '1/150;manuaddp %player% ultracosmetics.gadgets.melonthrower'  
     - '1/1000;manuaddp %player% ultracosmetics.emotes.cheeky' 
     - '1/1000;manuaddp %player% ultracosmetics.emotes.happy'  
   ASkyBlock:
     - 'give %player% 3 2'
     - '1/100;manuaddp %player% ultracosmetics.hats.golem' 
     - '1/100;manuaddp %player% ultracosmetics.hats.enderman'  
     - '1/100;manuaddp %player% ultracosmetics.hats.mario'  
     - '1/100;manuaddp %player% ultracosmetics.hats.luigi'  
     - '1/100;manuaddp %player% ultracosmetics.hats.batman'  
     - '1/150;manuaddp %player% ultracosmetics.gadgets.melonthrower'  
     - '1/1000;manuaddp %player% ultracosmetics.emotes.cheeky' 
     - '1/1000;manuaddp %player% ultracosmetics.emotes.happy'  
rewards:

# these rewards are when a player reaches a certain amount of votes

# these rewards are the same as above but per world if rewards by world are enabled

  world:

**Comment by teozfrank** [comment]
Closed, old issue, if this issue persists please create a new one and it will be addressed.
