### ISSUE TITLE
Commands not being run

### ISSUE THREAD

**Issue by AdamIanMurphy** [teozfrank/UltimateVotes#8]
I beleive it is a config issue, but upon further investigation, i could not find the issue. Could i get some help please?

http://pastebin.com/C4eXH7PQ

**Comment by teozfrank** [comment]
What commands are not being ran?

**Comment by AdamIanMurphy** [comment]
From testing in both worlds, the only commands that work is the ones that give me cookies (world), soulsand(simpleSB) and stone pick axe (world)

Console output:

http://pastebin.com/7eHTJKfx

**Comment by AdamIanMurphy** [comment]
The way it is intended to work is the first line of commands are the rewards you get every time you vote, but you don't even get them, then there is obviously the lucky votes, and I've used a test vote a bunch of times via mctools.org and i have never gotten a lucky vote.

**Comment by teozfrank** [comment]
"The way it is intended to work is the first line of commands are the rewards you get every time you vote,"

What first line of commands?

**Comment by AdamIanMurphy** [comment]
By first line of commands if you look at the config i sent, i refer to these two lines, 1 for each world of course
   world:
     - 'points give %player% 1;eco give %player% 100;crate key %player% vote;enjin broadcast &0[&c&lSS&8MC&0] &b&l%player%&r &eJust voted! They earned 1 vote point, 1 vote crate key and $100!'
  SimpleSB:
    - 'points give %player% 1;eco give %player% 150;give %player% 17 32;give %player% grass 32;crate key %player% SkyVote;Enjin broadcast &0[&c&lSS&8MC&0] &b&l%player% &eJust voted! They earned 1 vote point, $150, 32 logs, 32 grass and a SkyVote crate key!'

To my understanding, they should run everytime someone votes, in the respected world. But they dont

**Comment by teozfrank** [comment]
Only if the player is in that world at the time of the reward, otherwise no.

**Comment by teozfrank** [comment]
Closed, old issue, if this issue persists please create a new one and it will be addressed.
